### ISSUE TITLE
Types not exported

### ISSUE THREAD

**Issue by austinm911** [stacksjs/bun-spreadsheets#4]
### Describe the bug

Types don't appear to export correctly on 0.1.0? I am unable to import `type Content` for example
![image](https://github.com/user-attachments/assets/bc7f3e00-0bd7-4a39-90e3-ce3c58e5c821)

### Reproduction

see img

### System Info

```Shell
System:
    OS: macOS 15.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 109.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.6.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 1.1.30 - /opt/homebrew/bin/bun
    Watchman: 2024.09.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 127.1.68.128
    Chrome: 120.0.6099.129
    Safari: 18.0
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/stacksjs/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/stacksjs/contributing).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chrisbbreuer** [comment]
Thanks for reporting this. I should get this resolved today! 🙏

**Comment by chrisbbreuer** [comment]
This did take quite a bit longer than expected and the reason here is that we developed our own dts emitter to not have the overhead of OXLint. Bun is incredibly fast as well.

This should be resolved now in v0.1.2 🎉

**Comment by austinm911** [comment]
@chrisbbreuer hey sorry to bug you again, I'm still not getting any types resolved when using some of these functions. Of course I can manually build up the data object `const data: Content = { ... }` and pass it in, but I guess just wanted to point out the issue

<img width="968" alt="Image" src="https://github.com/user-attachments/assets/0e66227a-5417-4e61-8902-d2b87cab7b4f" />

**Comment by austinm911** [comment]
@chrisbbreuer this is still broken
